server:
  port: 8443  # HTTPS服务监听的端口号，默认为443，这里使用了8443，避免与系统端口冲突
  ssl:
    key-store: classpath:localhost.p12 # 使用mkcert工具生成的本地可信任证书
    key-store-password: changeit  # 密钥库的密码
    key-store-type: PKCS12  # 密钥库类型，PKCS12是一种广泛支持的格式
#    key-alias: myalias  # 密钥库中密钥的别名
  http2:
    enabled: true # 启用HTTP/2协议，确保使用的服务器支持HTTP/2
