spring:
  datasource: # 配置数据源
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource  # 默认的连接池
  data:
    redis:
      host: redis
      port: 6379
      password: redis@123
      client-type: lettuce  # 客户端类型，默认为lettuce，可选jedis
      lettuce:
        pool:
          max-active: 50 #最大活动连接，默认8个
          min-idle: 10  #池中“空闲”连接的最大数目。默认0
          max-idle: 50  #池中“空闲”连接的最大数目。使用负值表示空闲连接数不受限制，默认8
          max-wait: 5000  # 当连接池耗尽时，在抛出异常之前，连接分配应该阻塞的最大时间。使用负值表示无限期阻塞。默认-1
mybatis: # 配置MyBatis
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰命名
