server:
  port: 9999
management:
  endpoints:
    web:
      exposure:
        include: '*' # 所有的Actuator端点都将通过Web暴露
  endpoint:
    health:
      show-details: always # 总是显示详细的健康信息
      access: unrestricted # 对健康检查端点的访问没有限制。
